--Criação do usuário AGLM
CREATE USER AGLM IDENTIFIED BY "123Fatec";

--Permissões
GRANT UNLIMITED TABLESPACE TO AGLM;
GRANT CONNECT, RESOURCE TO AGLM;
GRANT CREATE SESSION TO AGLM;

--Criação das tabelas
CREATE TABLE AGLM.FUNCIONARIO
(
	"FNC_ID" NUMBER(6,0) ,				-- ID DA CARTEIRA
    "FNC_NOME" VARCHAR (255),
    "FNC_CARGO" VARCHAR (255),
	"FNC_SALARIO" NUMBER(8,2) DEFAULT 0
);

--PRIMARY KEY
ALTER TABLE AGLM.FUNCIONARIO
	ADD CONSTRAINT PK_FNC PRIMARY KEY (FNC_ID);
    
-- Criação da sequence
CREATE SEQUENCE AGLM.SQ_FNC 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- Triggers para pegar valor da sequence
create or replace
TRIGGER AGLM.TG_SQ_FNC
BEFORE INSERT ON AGLM.FUNCIONARIO
FOR EACH ROW
BEGIN
  :new.FNC_id := AGLM.SQ_FNC.NEXTVAL;
END;