--Criação do usuário C##AGM
CREATE USER C##AGM IDENTIFIED BY "123Fatec" container=all;

--Permissões
GRANT UNLIMITED TABLESPACE TO C##AGM;
GRANT CONNECT, RESOURCE TO C##AGM;
GRANT CREATE SESSION TO C##AGM;

--Criação das tabelas
CREATE TABLE C##AGM.FUNCIONARIO
(
	"FNC_ID" NUMBER(6,0) ,				-- ID DA CARTEIRA
    "FNC_NOME" VARCHAR (255),
    "FNC_CARGO" VARCHAR (255),
	"FNC_SALARIO" NUMBER(8,2) DEFAULT 0
);

--PRIMARY KEY
ALTER TABLE C##AGM.FUNCIONARIO
	ADD CONSTRAINT PK_FNC PRIMARY KEY (FNC_ID);
    
-- Criação da sequence
CREATE SEQUENCE C##AGM.SQ_FNC 
INCREMENT BY 1 
START WITH 1 
NOCACHE
;

-- Triggers para pegar valor da sequence
create or replace
TRIGGER C##AGM.TG_SQ_FNC
BEFORE INSERT ON C##AGM.FUNCIONARIO
FOR EACH ROW
BEGIN
  :new.FNC_id := C##AGM.SQ_FNC.NEXTVAL;
END;